language: R
sudo: false
cache: packages
after_success:
- Rscript -e 'covr::codecov()'
env:
  global:
    secure: KQ1A9OlL/ZqgHh6aCdxVDGQ2aMv9OTOMakk/PgTNx71HTGSt5rRv3K5icsbPQPMM8USZ/t7FbUCMNlO0Lw/wD0pZfZOYOlzBcDeV6BGCP8nLmyzHjS15qFJnNGdCW379Z5VZ0qwFR1govvcPAXlQmZH4ATAsc0JpR7HvsQcwpuLUWT5b2MpyX96nMey1eHxAInr7kNQdbi2rb4kakO6tF6AFLFA0pFj0QhPYZpHe0eVvFdVT7xFQErkjVzqeCUCwb2eQI6ovQdHTVqiNBYaAh9YLjnIpWcTSZVMcR1w+e4YlPttbCj238EHk7uRv688KZCktT3AG6/tG+KbuzyXycX28L39RRt/6rg06oHyiaqJyJ2pXYZR5/7E8xmlFG2dusLmb+gSvFSHCuAvsMqcch0+kvLsT47vbPh2Cru9nh3/XV3O/sh1pzXBeu8Fay6cHTQDVzRyx+EAKnv5K9iAy+ovmL8IoFnNfsLbDsHtONAUoieLHOgE2HhUJoXut3NVxz2zQhPJOt81q6UhzOU0B4IXmQaUicFRydVhEn0mkMlE4IDElzhcKqdK/oHCMvWjnFok92RhwnYBnbxXEsW6MEjTgFTplafNABldt5Lu7TK0wdN+VMHd9TH8Ov+oeLOl4xs64hQjgSg2C3DAR2Nd29tCxF1lAyjCX2DLtC67fwoI=
