language: R
sudo: false
cache: packages
after_success:
- Rscript -e 'covr::codecov()'
- Rscript --verbose -e "install.packages('remotes')" -e "remotes::install_github('yonicd/covrpage')" -e "remotes::install_github('yonicd/vcs')" -e "path <- file.path(tempfile(pattern='covrpage-'),'pkgfiles')" -e "dir.create(path,recursive = TRUE)" -e "vcs::sparse_checkout(repo_url = 'https://github.com/yonicd/covrpage.git', dest.dir = path, queries = '*',depth = 1)" -e "setwd(path)" -e "covrpage::covrpage('.',preview = FALSE,auto_push = TRUE)"
