# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript --verbose -e "covrpage::covrpage(pkg = '.', preview = FALSE, auto_push = TRUE)"
  