language: R
sudo: false
cache: packages
after_success:
- Rscript -e 'covr::codecov()'
env:
  global:
  - secure: tenzQVJmvJsSMcJ3al46WLkLQ3zCYoBTSK7/JpyLG5UIwhW4xHaHLzR6/mGCdqAhpp+r1Dnb7BS5ugujJteU/zXjeCrLVzOZdVOJEhVq4cK+IB4sx16xk8MFsXzXJz6yObHqYPVyMXx0ZB8+wdV6j3xiUz3ABh6Tp9oKZDEt28D+fNFb2qRSqO98R2XuyKTVUF+5xRZqrew3pdgAIuItXamH8/ICk/xonGgg/i6zTcgTYMdxHLHVq+YgB2wIfMXfh3H0ezBeSeyzKSqIt/ofAJbG5Yue9c6ZaZ0nZEQJvVVeUCOOqY2suvtUVMWcEs9Uj9AoIktQwkhnysmmUXIBD9rJR+o0gTF07EsIKlUlmzzyDIdgm1LMWT4XPrlV4D5FxIpN6A6TRn7D/ne6JRDAKrSFReo6Yt1z/9ycoRSqpMKxVTzLPctKD59FFjahkX1qZ8SUh9An6jgwq4r7ahmGyA7ZiGcjC70sr0yjcRLNzjOjtih7REuvZpZgFB3RIjRDYzJUURl5g5BGbjGcn3v6gCySZolKgjcGlX/ZjRYZKCcc6I31CYRQm4wckMS8pLXjNlEyOQbDpqtMcpE/STx/SRuHVHwn1R22FEgjFwWdPp1IjUPexro2gObd+3uCbLqmpSjAAlOVhapwobLyVFgPi4934ec+lTUQPQ4CZjrWLwc=
